name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Generate Changelog
        id: changelog
        run: |
          echo "::set-output name=changelog::$(npx auto-changelog --template keepachangelog)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_SECRET }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            ---
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_SECRET }}
          publish_dir: ./build

      - name: Update Release with deployment link
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT_SECRET }}
          script: |
            const url = `https://${{ github.repository }}.github.io/${{ github.event.repository.name }}/`
            github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ steps.create_release.outputs.id }},
              body: `Changes in this Release\n---\n${{ steps.changelog.outputs.changelog }}\n\nDeployment: [${url}](${url})`
            })

      - name: Close issue
        id: close_issue
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT_SECRET }}
          script: |
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'RELEASE',
              sort: 'created',
              direction: 'desc'
            })
            const releaseIssue = issues.find(issue => issue.title.includes(`Release ${{ github.ref }}`))
            if (releaseIssue) {
              await github.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: releaseIssue.number,
                state: 'closed'
              })
            }